Algoritmo "LER VARIAVEL"
// função: ler doi valores para a variavel A e B, e efetuar as trocas
// dos valore
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : ler nome do aluno e ntas
// Autor(a)    : maycon
Var
a, b, troca:inteiro

Inicio
// Seção de Comandos
escreval("digite o valor(numerico) da variavel A:")
leia(a)
escreval("digite o valor(numerico) da variavel B:")
leia(B)
troca
Fimalgoritmo